# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 18:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tour name')),
                ('slug', models.SlugField(help_text='Should be short, only contain lowercase letters, numbers, dots, and dashes, and must be unique among your tours. You can also choose to use a random value. This will be used in URLs, order codes, invoice numbers, and bank transfer references.', validators=[django.core.validators.RegexValidator(message='The slug may only contain letters, numbers, dots and dashes.', regex='^[a-zA-Z0-9.-]+$')], verbose_name='Short form')),
                ('tour_type', models.CharField(blank=True, help_text="Enter one of the following 'Walking', 'Cycling', 'Coach'Other tour types TBC", max_length=100)),
                ('tour_style', models.CharField(blank=True, help_text="Enter one of the following 'Street Food', 'Comfort Food', 'Izakaya food & Drink'Other tour styles TBC", max_length=100)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('live', models.BooleanField(default=False, verbose_name='Tour is live')),
                ('currency', models.CharField(help_text="Enter the three letter currency code 'YEN'", max_length=3, verbose_name='Tour currency')),
                ('time_from', models.TimeField(verbose_name='Tour start time')),
                ('time_to', models.TimeField(blank=True, null=True, verbose_name='Tour end time')),
                ('start_location', models.TextField(blank=True, max_length=200, null=True, verbose_name='Start Location')),
                ('start_location_link', models.URLField()),
                ('start_location_image', models.ImageField(blank=True, null=True, upload_to='static/images/location/')),
                ('end_location_link', models.URLField()),
                ('tour_places', models.SmallIntegerField(blank=True, null=True)),
                ('rating_culture', models.SmallIntegerField(blank=True, null=True)),
                ('rating_fooddrink', models.SmallIntegerField(blank=True, null=True)),
                ('rating_adventure', models.SmallIntegerField(blank=True, null=True)),
                ('vegetarian_option', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('walking_distance', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
            },
        ),
    ]
