# Generated by Django 2.0.2 on 2018-03-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_illustration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='illustration',
            field=models.ImageField(default='images/LogoLarge.svg', upload_to="{% static 'images/blog/' %}"),
        ),
    ]
