# Generated by Django 2.0.2 on 2018-03-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180311_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='illustration',
            field=models.ImageField(blank=True, default='images/LogoLarge.svg', null=True, upload_to='blog/'),
        ),
    ]
